### ISSUE TITLE
Support for HTTP proxy

### ISSUE THREAD

**Issue by andylhxu** [clarete/hackernews.el#27] opened 2017-06-12 14:52 UTC
Are there supports for setting up HTTP proxies for the HN emacs client?

**Comment by clarete** [comment] 2017-06-26 13:22
There isn't any support yet but that's indeed a good idea!

**Comment by andylhxu** [comment] 2017-06-27 14:42
It would be nice to have it since I bet a lot of the use cases are inside internal networks.

**Comment by clarete** [comment] 2017-06-30 01:03
Hi @andylhxu, I took some time to look a lil deeper at the issue.

`hackernews.el` uses `url.el`, I believe that setting `url-proxy-services` might suffice.
I grabbed the following snippet from a [StackOverflow answer](https://stackoverflow.com/questions/1595418/emacs-behind-http-proxy):

```emacs-lisp
(setq url-proxy-services '(("no_proxy" . "work\\.com")
                           ("http" . "proxy.work.com:911")))
```

**Comment by andylhxu** [comment] 2017-07-06 14:54
@clarete Yep, I have the proxy set up because i need to packages from melpa from the internal network. However, it didn't work for the hn client. I'll try one more time later today.

**Comment by clarete** [comment] 2017-07-06 15:59
@andylhxu, let's reopen this bug if your test confirms that it's not enough.

**Comment by andylhxu** [comment] 2017-07-08 05:19
confirmed, the proxy configuration with `url-proxy-service` is not sufficient.

**Comment by clarete** [comment] 2017-07-10 03:06
OK! Let's reopen the issue and figure out how it could work! Thanks for testing that!

**Comment by basil-conto** [comment] 2017-08-27 17:58
For what it's worth, here are the relevant nodes from the `url.el` manual on [proxies](https://www.gnu.org/software/emacs/manual/html_node/url/Proxies.html) and [gateways in general](https://www.gnu.org/software/emacs/manual/html_node/url/Gateways-in-general.html).

**Comment by basil-conto** [comment] 2018-02-01 01:07
@andylhxu It would be very helpful if you could provide some more information on this. For example, what is your `emacs-version`? Have you tried setting `url-debug` to `t` and inspecting the contents of the `*URL-DEBUG*` buffer?

The only differences between `package.el` and `hackernews.el` in their usage of `url.el` are:
1. `package-archives` used to default to HTTP addresses in older versions of Emacs (but not anymore), whereas `hackernews.el` always uses HTTPS access points; and
2. `package.el` defaults to asynchronous retrieval via `url-retrieve`, whereas `hackernews.el` always does synchronous retrieval via `url-retrieve-synchronously`.

Re: (1), can you please check whether your `package-archives` include any HTTPS addresses? Do other uses of TLS work for you, e.g. <kbd>M-x</kbd>`eww`<kbd>RET</kbd>`https://gnu.org`<kbd>RET</kbd>? Newer versions of Emacs have GnuTLS built-in, which makes working with TLS much faster and more reliable from what I gather. If you are on an older Emacs, perhaps it's just a matter of modifying your GnuTLS configuration.

Re: (2), can you try setting `package-menu-async` to `nil` and see if <kbd>M-x</kbd>`list-packages`<kbd>RET</kbd> still works for you?

**Comment by basil-conto** [comment] 2018-02-08 15:37
I have a feeling this issue might be caused by GNU Emacs [bug#11788](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=11788), which should be fixed in Emacs 26.

@andylhxu Any chance you can try it out in [Emacs 26](http://alpha.gnu.org/gnu/emacs/pretest/) and report back?

Either way I'm closing this issue as I don't think there is much `hackernews` can do. If the proxy still does not work for you in Emacs 26, please consider filing a bug via <kbd>M-x</kbd>`report-emacs-bug`<kbd>RET</kbd>.

**Closed by basil-conto** 2018-02-08 15:37 UTC
Labels: needinfo

**Comment by andylhxu** [comment] 2018-02-18 02:02
Sorry for not following this up on time. I will definitely try it out and report back asap 👍

**Comment by basil-conto** [comment] 2018-02-18 02:16
> Sorry for not following this up on time. I will definitely try it out and report back asap

No worries and good luck. :)
